# Description
    Demultiplex ERA Rhizosphere samples: run1

# Setting variables

In [1]:
workDir = '/home/bryan/ERA/'
seqDir = '/home/bryan/ERA/data/MiSeq/20170417_run1/'

metadataFile = 'ERA_MappingFile.txt'
read1_file = 'read1.fq'
read2_file = 'read2.fq'
index_read1_file = 'index1.fq'
index_read2_file = 'index2.fq'
read12_screed_file = 'pear_merged-2017-04-18.assembled.fastq_screed'

# Init

In [2]:
import os
import screed
import pandas as pd
from glob import glob
from collections import Counter
import matplotlib.pyplot as plt
import numpy as np
#from ggplot import *
import re
import scipy.stats as stats

In [3]:
if not os.path.isdir(workDir):
    os.mkdir(workDir)

In [4]:
%load_ext rpy2.ipython

In [5]:
%%R
library(ggplot2)
library(dplyr)
library(tidyr)
library(gdata)

Error in library(gdata) : there is no package called ‘gdata’

/opt/anaconda2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning:
Attaching package: ‘dplyr’


  warnings.warn(x, RRuntimeWarning)
/opt/anaconda2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: The following objects are masked from ‘package:stats’:

    filter, lag


  warnings.warn(x, RRuntimeWarning)
/opt/anaconda2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


  warnings.warn(x, RRuntimeWarning)
/opt/anaconda2/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in library(gdata) : there is no package called ‘gdata’

  warnings.warn(x, RRuntimeWarning)

## Uncompressing with four files output

In [6]:
uncompFiles = glob(os.path.join(seqDir, 'index?.fq'))

if len(uncompFiles) != 2:
    !cd $seqDir; \
        pigz -k -d -p 24 index?.fq.gz

In [ ]:
# Generate screed database from index files

In [ ]:
#long processessing time
os.chdir(seqDir)
screed.read_fastq_sequences(index_read1_file)
screed.read_fastq_sequences(index_read2_file)

## Checkpoint: define index screed files to skip above step

In [ ]:
index_read1_screed = index_read1_file + '_screed'
index_read2_screed = index_read2_file + '_screed'

# Demultiplex

In [ ]:
# rev-comp functions
def complement(seq): 
    idx = {'A': 'T', 'C': 'G', 'G': 'C', 'T': 'A', 'N':'N'} 
    idx.update( {x.lower():y.lower() for x,y in idx.items()} )
    return ''.join(idx[x] for x in list(seq))

def revComp(seq):
    seq = seq[::-1]
    return complement(seq)

In [ ]:
# loading/editing metadata

df_meta = pd.read_table(os.path.join(workDir,metadataFile), delimiter="\t")
df_meta.columns = ['Sample'] + list((df_meta.columns)[1:])

df_meta['Barcode_FR'] = [(revComp(y) + x).lower() for x,y \
                         in zip(df_meta.fwd_barcode,df_meta.rev_barcode)]
#df_meta['Barcode_FR'] = [y.lower() + x.lower() for x,y \
#                         in zip(df_meta.fwd_barcode,df_meta.rev_barcode)]


## format of barcode=>sample dict: [revBarcode=read1 + fwdBarcode=read2] : sampleID
map_d = {x:y for x,y in zip(df_meta.Barcode_FR, df_meta.Sample)}

In [ ]:
df_meta

In [49]:
# resulting dict of sample => barcode_FR 
n_print = 5
[(map_d.keys()[i], map_d[map_d.keys()[i]]) for i in xrange(n_print)]

[('tgagtacgactatctg', 'ERA-T1_1-2d_85'),
 ('gatctacgcgtgagtg', 'ERA-T1_4-3d_85'),
 ('tatagcgagacaccgt', 'NegControl_A'),
 ('gtaacgagcgtgagtg', 'ERA-T0_3-4c_0'),
 ('tatagcgatacgagac', 'ERA-T2_4-5a_85')]

In [50]:
# loading screed databases 
os.chdir(seqDir)

ir1db = screed.ScreedDB(index_read1_screed)
ir2db = screed.ScreedDB(index_read2_screed)
amp_db = screed.ScreedDB(read12_screed_file)

In [51]:
# demultiplexing: naming reads by sample

outFile = re.sub('fastq_screed', 'dmult.fastq', read12_screed_file)

counter = 0
unassigned = 0
cnt = Counter()
outFile = os.path.join(workDir, outFile)
c = 0
with open(outFile, "w") as out:
    for rec in amp_db.itervalues():
        # debug
        #c += 1
        #if c > 10000:
        #    break
            
        index_concat = ir1db[rec["name"]]["sequence"] + ir2db[rec["name"]]["sequence"]
        
        try:
            new_name = map_d[index_concat.lower()] + "_" + str(counter) #case sensitive
        except KeyError:
            unassigned += 1
            continue
        counter += 1
        cnt[map_d[index_concat.lower()]] += 1 #case sensitive
        s, q = rec["sequence"], rec["quality"]
        out.write("@%s orig_name=%s\n%s\n+\n%s\n"%(new_name,rec["name"],s,q))
        
        
print "Unable to assign %s reads to samples"%unassigned

Unable to assign 3140123 reads to samples

## Checkpoint: define outfile for next command without running above.

In [56]:
outFile = '/home/bryan/ERA/data/MiSeq/20170417_run1/pear_merged-2017-04-18.assembled.dmult.fastq'

In [57]:
# number of sequences
n_lines = !wc -l $outFile
n_lines = int(re.sub(' .+', '', n_lines[0]))
print 'Number of sequences: {}'.format(n_lines/4)

Number of sequences: 14036217

# Stats on sequences

## Number of sequences per sample

In [58]:
# counting sequences for each sample
re_seqName = re.compile(r'_\d+ orig_name.+')

seq_cnt = dict()
with open(outFile, 'r') as fn:
    for line in fn.readlines():
        if re.search(re_seqName, line):
            sampleName = re.sub(re_seqName, '', line).rstrip().lstrip('@')
            try:
                seq_cnt[sampleName] += 1
            except KeyError:
                seq_cnt[sampleName] = 1

In [59]:
# converting to dataframe
df_seq_cnt = pd.DataFrame(seq_cnt.items(), columns=['Sample', 'seq_count'])
df_seq_cnt

               Sample  seq_count
0     ERA-T1_3-3a_170      34912
1       ERA-T3_2-5c_0      50256
2       ERA-T3_3-5c_0      50903
3     ERA-T3_4-3d_170      99796
4       ERA-T3_2-3d_0      44601
5       ERA-T1_3-4c_0      29330
6      ERA-T2_2-1c_85      68659
7       ERA-T3_1-4b_0      48070
8    PostiveControl_C         45
9       ERA-T3_1-3c_0      51283
10     ERA-T1_1-3c_85      53610
11      ERA-T3_2-5a_0      95057
12    ERA-T1_1-2d_170      59288
13     ERA-T3_4-4a_85      77801
14     ERA-T2_2-4b_85      71930
15     ERA-T2_3-5c_85      44491
16     ERA-T2_1-2a_85      48409
17    ERA-T3_1-5a_170      46357
18     ERA-T3_2-5a_85      74556
19      ERA-T1_2-2d_0      63740
20      ERA-T1_1-4a_0      67009
21     ERA-T2_2-2d_85     108210
22     ERA-T1_3-2c_85     116369
23      ERA-T1_4-1b_0      40542
24      ERA-T3_3-2c_0      32319
25    ERA-T1_4-3d_170      91410
26    ERA-T1_2-2c_170      44697
27    ERA-T3_2-3b_170      66273
28      ERA-T1_3-1c_0      43455
29      ERA-T1_4-2c_0      70202
..                ...        ...
222    ERA-T2_2-3b_85      31460
223    ERA-T2_1-4a_85      45574
224    ERA-T2_1-2c_85      53010
225   ERA-T3_2-2b_170      62224
226     ERA-T3_4-5b_0      53212
227    ERA-T2_3-4d_85      33495
228    ERA-T2_3-1b_85      57475
229    ERA-T2_1-4b_85      76605
230     ERA-T0_2-2c_0      98619
231   ERA-T3_1-3c_170      51222
232    ERA-T2_2-3d_85      31081
233      NegControl_A        283
234   ERA-T3_4-5b_170      74826
235    ERA-T1_1-2c_85      57703
236    ERA-T2_3-5b_85      43469
237    ERA-T2_1-4c_85      36004
238    ERA-T2_4-3b_85      25945
239    ERA-T2_1-1d_85      56407
240    ERA-T3_1-4a_85      44255
241    ERA-T2_2-4d_85      45009
242     ERA-T0_2-3b_0      26272
243     ERA-T1_2-2c_0      68214
244    ERA-T2_3-1a_85      32424
245    ERA-T3_4-1b_85      51030
246   ERA-T3_3-1d_170      28211
247   ERA-T1_2-5c_170      65862
248    ERA-T3_1-4b_85      33351
249      NegControl_B       1439
250   ERA-T3_2-2c_170      53925
251    ERA-T2_4-1b_85      60962

[252 rows x 2 columns]

In [63]:
df_seq_cnt.sort(['seq_count'])

/opt/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

               Sample  seq_count
177       IndexQC_Rev          1
8    PostiveControl_C         45
185      PosControl_B         80
91       NegControl_C         97
181      PosControl_A        246
233      NegControl_A        283
193  NegControl_Plate        373
249      NegControl_B       1439
32    ERA-T1_2-3b_170      17321
59    ERA-T1_3-4c_170      21345
198    ERA-T1_1-2b_85      23156
162   ERA-T3_1-2b_170      24136
41     ERA-T1_3-5c_85      24609
175    ERA-T2_4-4d_85      25786
238    ERA-T2_4-3b_85      25945
242     ERA-T0_2-3b_0      26272
152     ERA-T3_3-1a_0      26338
179     ERA-T3_4-4a_0      26475
176    ERA-T3_3-1d_85      26878
209    ERA-T2_3-1c_85      27116
51     ERA-T1_2-2c_85      27337
54     ERA-T2_1-3a_85      27470
40    ERA-T3_3-3a_170      28054
246   ERA-T3_3-1d_170      28211
5       ERA-T1_3-4c_0      29330
216     ERA-T1_3-3a_0      29496
99     ERA-T1_4-1a_85      29668
232    ERA-T2_2-3d_85      31081
222    ERA-T2_2-3b_85      31460
210     ERA-T1_1-2d_0      32289
..                ...        ...
77    ERA-T3_4-3b_170      87778
34     ERA-T3_4-3d_85      88529
124    ERA-T2_4-5c_85      89731
130    ERA-T2_4-3d_85      89955
46     ERA-T2_2-1d_85      90112
74     ERA-T1_2-3b_85      91319
25    ERA-T1_4-3d_170      91410
132     ERA-T3_4-3d_0      92558
104   ERA-T3_2-2d_170      93276
78      ERA-T1_2-3b_0      94337
55     ERA-T1_2-3d_85      94894
11      ERA-T3_2-5a_0      95057
197    ERA-T3_2-2b_85      96263
66     ERA-T2_1-5a_85      96597
169   ERA-T3_3-2c_170      97278
172   ERA-T1_1-5a_170      98441
230     ERA-T0_2-2c_0      98619
3     ERA-T3_4-3d_170      99796
64      ERA-T0_1-5a_0     101930
94     ERA-T2_4-3c_85     102061
21     ERA-T2_2-2d_85     108210
35     ERA-T2_2-4a_85     109752
107     ERA-T1_2-5c_0     110675
70      ERA-T3_2-3b_0     114737
22     ERA-T1_3-2c_85     116369
68      ERA-T3_2-2b_0     117186
67           MockComm     118567
149   ERA-T3_2-5a_170     134894
36      ERA-T0_4-1a_0     146132
81      ERA-T0_4-3d_0     185838

[252 rows x 2 columns]